[package]
name = "vader_sentiment_api"
version = "0.1.0"
authors = ["Tsepo Ramaisa <tseporamaisa@gmail.com>"]
edition = "2018"



[dependencies]
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
maplit = "1.0.2"
lazy_static = "1.4.0"